### ISSUE TITLE
npm exit when I try to add background image in the less file.

### ISSUE THREAD

**Issue by kchjxxgh** [fomenyesu/egg-restapi-module-tool#1]
I failed to add background image in the less. Could you please help me?

`.welcome {
  height: 328px;
  background: url(../img/yay.jpg) no-repeat center 0;
  background-size: 388px 328px;
}` 

> 10% building modules 0/1 modules 1 active ...rous\static\src\routes\IndexPage.lessP:\workspace\node_modules\loader-runner\lib\loadLoader.js:35
                        throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
                        ^

Error: Module 'P:\workspace\node_modules\url\url.js' is not a loader (must have normal or pitch function)
    at loadLoader (P:\workspace\node_modules\loader-runner\lib\loadLoader.js:35:10)
    at iteratePitchingLoaders (P:\workspace\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (P:\workspace\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (P:\workspace\node_modules\webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (P:\workspace\node_modules\webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (P:\workspace\node_modules\webpack\lib\Compilation.js:146:10)
    at factoryCallback (P:\workspace\node_modules\webpack\lib\Compilation.js:329:11)
    at factory (P:\workspace\node_modules\webpack\lib\NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (P:\workspace\node_modules\webpack\lib\NormalModuleFactory.js:99:14)
    at P:\workspace\node_modules\tapable\lib\Tapable.js:250:11

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "client"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! vigorous@1.0.0 client: `webpack-dev-server --port 8008 --inline --hot --watch --progress --config ./static/build/webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vigorous@1.0.0 client script 'webpack-dev-server --port 8008 --inline --hot --watch --progress --config ./static/build/webpack.dev.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vigorous package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8008 --inline --hot --watch --progress --config ./static/build/webpack.dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vigorous
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vigorous
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     P:\workspace\npm-debug.log

**Comment by fomenyesu** [comment]
you can put you image file into /static/assets/img/yay.jpg , then you can use it like this:

.welcome { height: 328px; background: url(/static/assets/img/yay.jpg) no-repeat center 0; background-size: 388px 328px; }

or you can 

.welcome { height: 328px; background: url(/static/src/img/yay.jpg) no-repeat center 0; background-size: 388px 328px; }
