### ISSUE TITLE
麻烦问一下，用最新的代码启动项目通过8080 访问前端有跨域问题怎么解决？

### ISSUE THREAD

**Issue by lxj5891** [fomenyesu/egg-restapi-module-tool#13]
{ status: 404,
  message: 'Not Found',
  header:
   { vary: 'Origin',
     'access-control-allow-origin': 'http://127.0.0.1:8080',
     'accept-ranges': 'bytes' },
  body: undefined }
2018-01-21 16:23:02,649 WARN 76646 [-/127.0.0.1/-/3ms POST /user/authorize?t=1516522982459] nodejs.unauthorized_request: Unauthorized request: no authentication given

**Comment by youxfans** [comment]
#12 #9 @fomenyesu 
Duplicate of #
Duplicate of #

**Comment by lxj5891** [comment]
已经解决了 done

**Comment by fomenyesu** [comment]
good!

**Comment by fomenyesu** [comment]
跨域需要在 [config.default.js](https://github.com/fomenyesu/egg-restapi-module-tool/blob/master/config/config.default.js) 里面配置域名白名单。具体配置：
`
exports.security = {
  ignore: "/api/",
  domainWhiteList: [
    "http://127.0.0.1:8080",
    "http://10.180.144.212:8080",
    "http://localhost:8080"
  ],
...
`

**Comment by lxj5891** [comment]
3q

**Comment by lxj5891** [comment]
这个项目作为脚手架非常棒 ！！ 大力支持 ， 哈哈
