### ISSUE TITLE
前端界面登录报错401

### ISSUE THREAD

**Issue by beautycss** [fomenyesu/egg-restapi-module-tool#14]
![image](https://user-images.githubusercontent.com/16473160/35774086-8168d638-09a0-11e8-9b47-2ef476c09af9.png)

![image](https://user-images.githubusercontent.com/16473160/35774165-bd7b0ab8-09a2-11e8-90f7-33e0bcc63e23.png)

![image](https://user-images.githubusercontent.com/16473160/35774167-ca4582a0-09a2-11e8-9a6e-0e1c5fdcbdea.png)

#### 问题描述：
使用npm run dev启动，前端登录界面无法登录进去，一直报401错误。

后端界面能正常登录进去，后台接口访问正常，比如http://127.0.0.1:7001/api/restql/web_admin
我本地分别使用的 http://127.0.0.1:7001/ 和 http://127.0.0.1:8080/ 进行访问，白名单里都有。
npm插件都安装正常。

#### 本地配置：
mysql 5.6.35
node 9.2.0
npm 5.5.1

#### 疑问：
1. 这个401认证的问题如何解决？
2. static里service的app.js里请求的`/api/restql/users/${uid}`这个接口路径，但是现在最新的代码接口实际是`/api/restql/web_admin`，不是users了。

谢谢！

**Comment by fomenyesu** [comment]
1. for 401, run  npm install instead of "cnpm install" may help you.
2. static is fixed in the latest version.

 Thanks!

**Comment by fomenyesu** [comment]
After Installed, it's recommend to run npm run server in one console, and run npm run dev_static in another  console.

Then you will receive the log clearly.

**Comment by beautycss** [comment]
好的，谢谢，我试下。

**Comment by lucian-czh** [comment]
你密码给错了。。。你给的pass是：123，但是你用了md5加密进行对比，那么数据库pass应该是：202cb962ac59075b964b07152d234b70 @fomenyesu  @遇到此类问题的所有人。

**Comment by fomenyesu** [comment]
thanks!
I forgot to change it to 202cb962ac59075b964b07152d234b70 .
