### ISSUE TITLE
运行了 npm run dev 登录不进去

### ISSUE THREAD

**Issue by ghost** [fomenyesu/egg-restapi-module-tool#15]
npm install 后 npm run dev  登录页面输入用户名 密码 error
![error](https://user-images.githubusercontent.com/8219669/38124308-4ca8a12e-3413-11e8-9302-e16cdead0212.png)

**Comment by fomenyesu** [comment]
应该是你的mysql没有跑起来。服务端没有连上mysql。
npm install 之后需要导入数据到你的mysql数据库里。再启动mysql服务。
再运行npm run dev
