### ISSUE TITLE
运行后报错请问怎么处理

### ISSUE THREAD

**Issue by ghost** [fomenyesu/egg-restapi-module-tool#17]
win系统 npm install 没问题 运行npm  start时候报错[
![error](https://user-images.githubusercontent.com/8219669/38732751-fd715d54-3f51-11e8-963d-2ca4c854b27a.png)
](url)

**Comment by fomenyesu** [comment]
建议分开运行，检查server端是否正常开启。

使用 npm run server 运行server端 进行egg开发

使用 npm run dev_static 运行view端 进行react开发

看你的报错，很可能是server端没有正常启动导致。

运行server端需要开启你本地的mysql服务，导入testdb.sql的数据文件。还需要在egg的配置文件里配置你的数据库用户名密码。

如果你按照上面的方法，还无法解决，麻烦回复这个issue。谢谢~

**Comment by ghost** [comment]
小白一枚，我本地开了msql,我创建了一个表，把.sql文件导入了，我需要设置用户名,密码吗？egg配置不知道怎么弄，楼主可否给个链接看下，谢谢`

**Comment by ghost** [comment]
我创建了数据库导入了那个sql文件
![egg1](https://user-images.githubusercontent.com/8219669/38764817-921451f0-3fe8-11e8-9135-66bb0aaf73da.png)
然后egg的config配置也改了

![egg](https://user-images.githubusercontent.com/8219669/38764820-b0f1a1ea-3fe8-11e8-8677-936edda8d415.png)
但是输入了 admin 123 还是不行

**Comment by fomenyesu** [comment]
需要设置用户名密码
配置文件的地址在：
[config/config.local.js](https://github.com/fomenyesu/egg-restapi-module-tool/blob/master/config/config.local.js)

npm run server 之后可以看是否正常开启。如果没有连接上mysql会有报错信息。

你可以把输入admin 123 之后 终端显示的报错信息粘贴上来看下是什么问题。

**Comment by ghost** [comment]
![success](https://user-images.githubusercontent.com/8219669/38768316-6e1aa196-4024-11e8-84b1-8b6d8f2705e6.png)
可以了，接下来我增加接口后模块那分页怎么看不到我新增加的??

**Comment by fomenyesu** [comment]
模块管理是用来新增数据表的。新增数据表之后。在接口管理会出现对应数据表的restapi接口。用于增删改查。


通过接口管理添加的post数据，可以通过接口管理里的list获取到。

**Comment by fomenyesu** [comment]
问题解决
