### ISSUE TITLE
登陆后刷新，跳转到登陆页面

### ISSUE THREAD

**Issue by jackie19** [fomenyesu/egg-restapi-module-tool#18]
用7001端口访问，不能保持登陆状态？

**Comment by fomenyesu** [comment]
7001访问的是server的静态页面，里面的还是v1.0的内容。没有带oauth的。
可以使用
npm  run build 
把v2.0带oauth的静态页面编译一下。
再使用7001端口访问，就可以保持登录状态了。

如果还有问题，请持续跟进。谢谢！

**Comment by fomenyesu** [comment]
没有进一步的回复。
