### ISSUE TITLE
本地开发环境的数据连接如何配置，才不会弄脏环境？

### ISSUE THREAD

**Issue by kevin3274** [fomenyesu/egg-restapi-module-tool#2]
如直接修改config.local.js, 就会造成git显示有修改的内容，造成环境弄脏，有什么样的方法可以在本地配置后，只生效，而不需要上传？

**Comment by kevin3274** [comment]
如果将config.local.js更名为config.local.js.example，上传到源码中，然后开发人员在本地环境需要执行
cp config.local.js.example config.local.js , 然后修改对应于本地环境的连接，并且不需要上传到git, 添加.gitignore中config/config.local.js

**Comment by fomenyesu** [comment]
config.local.js 是本地的配置。生产环境配置是config.prod.js。开发的时候可以ignore掉config.local.js。不需要频繁更换config.local.js。

**Comment by kevin3274** [comment]
目前config.local.js在版本管理中，是不是需要将其从版本管理中移除？

**Comment by fomenyesu** [comment]
个人觉得不需要删除，方便开发的自己配置。

**Comment by fomenyesu** [comment]
我觉得config.local.js需要保留的。在git上拿下来之后
cp config.local.js.example config.local.js
这一步可以省略，因为cp之后还是会出现config.local.js文件，还是需要对这个文件进行配置。
谢谢~

**Comment by kevin3274** [comment]
如果config.local.js进行源码管理，那么在开发本地对其做修改后，git status总是会显示该文件的修改状态，我个人对此比较在意，希望代码区是『干净』的，所以才希望使用cp config.local.js.example config.local.js来解决

**Comment by fomenyesu** [comment]
你是想把config.local.js加入到ignore list 里？源码区只留下 config.local.js.example ?

**Comment by kevin3274** [comment]
是的，看来是我忘记添加gitignore了

**Comment by fomenyesu** [comment]
是啊。可以在开发本地使用gitignore

**Comment by kevin3274** [comment]
请教，本地如何使用gitignore，而不会弄脏work tree, 包括被源码中的.gitignore自己？
谢谢

**Comment by fomenyesu** [comment]
本地使用gitignore直接在git项目目录下配置就可以了。如果你不想提交gitignore文件，想在本地ignore文件。可以编辑.git/info/exclude文件，语法与.gitignore一致。
两个文件区别在于，exclude只用于设置本地需要忽略的文件，而.gitignore是公共需要排除的。
