### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by YMFL** [fomenyesu/egg-restapi-module-tool#21]
<img width="1417" alt="wx20180829-150252 2x" src="https://user-images.githubusercontent.com/18079377/44771143-c0a3ac80-ab9c-11e8-9c60-822389a35964.png">

**Comment by fomenyesu** [comment]
看提示是连接数据库错误。
需要先把数据导入到MySQL数据库里，把数据库的用户名密码配置到
config/config.local.js 文件里才能正常运行的。
