### ISSUE TITLE
新增模块报错

### ISSUE THREAD

**Issue by zhangguijian** [fomenyesu/egg-restapi-module-tool#22]
![image](https://user-images.githubusercontent.com/41320802/44966842-2e225500-af70-11e8-88d9-81f1b89247b8.png)

![image](https://user-images.githubusercontent.com/41320802/44966846-39758080-af70-11e8-91ca-5ba6a24022b2.png)

**Comment by zhangguijian** [comment]
当我run test 的时候
![image](https://user-images.githubusercontent.com/41320802/44978419-4bb9e380-af9d-11e8-99f3-f0b285290bca.png)
我跟着官方文档中的mysql，是可以连接的。

**Comment by fomenyesu** [comment]
第一个问题，你用的是cnpm install么？淘宝的npm镜像。上面的oauth插件有问题。
需要使用 npm install 安装。

第二个，run test 的时候使用的数据库连接配置是: config.unittest.js 这个文件的配置。
官方上应该也写了。

run test 的脚本现在在 oauth的版本运行还有问题，需要在 router.js 里面把oauth关掉。
就这块的代码：app.oAuth2Server.authenticate()。

有进一步的问题麻烦与我沟通。谢谢~

**Comment by zhangguijian** [comment]
ok
