### ISSUE TITLE
Can not start

### ISSUE THREAD

**Issue by woAo** [fomenyesu/egg-restapi-module-tool#24]
![qq 20181010142742](https://user-images.githubusercontent.com/42798367/46717041-d4145e00-cc98-11e8-9060-ae2dd7959631.png)

![qq 20181010142807](https://user-images.githubusercontent.com/42798367/46717052-daa2d580-cc98-11e8-9f1a-639330a75912.png)

**Comment by woAo** [comment]
Is it missing other things you need?

**Comment by woAo** [comment]
已经解决了，缺少`npm i egg-bin --save-dev`

**Comment by woAo** [comment]
Solved, missing`npm i egg-bin --save-dev`

**Comment by fomenyesu** [comment]
Thanks for your issue !
If there's any problem, please let me know.
