### ISSUE TITLE
Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by MakerGYT** [fomenyesu/egg-restapi-module-tool#25]
使用mysql 8.0，数据库已导入，启动时报错
```
Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

**Comment by fomenyesu** [comment]
mysql 版本的问题。我试过下面的方法可以解决：

mysql> alter user 'root'@'localhost' identified with mysql_native_password by '123456';
Query OK, 0 rows affected (0.10 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.01 sec)
