### ISSUE TITLE
关于数据库配置与使用

### ISSUE THREAD

**Issue by kevin3274** [fomenyesu/egg-restapi-module-tool#3]
我打算运行该项目，按您的说明，可以正常运行，但数据库不存在，页面无法正常工作，是否可以添加对数据库使用的说明，首次使用，后面如需要改动结构该如何处理？

**Comment by fomenyesu** [comment]
install mysql start mysql import testdb.sql to mysql

readme里有数据库的安装说明。

**Comment by fomenyesu** [comment]
当然这个说明有点简陋，欢迎你补充更详细的说明。谢谢~
