### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by azhengzheng** [fomenyesu/egg-restapi-module-tool#5]
请问 怎么设置里面的端口问题 我有两个项目 感觉好像都是8000就会冲突只显示一个项目 求教

**Comment by fomenyesu** [comment]
这个项目应该没有使用8000才对。你只显示一个项目，很有可能是因为你的node版本太低导致的。因为egg需要node版本在6.0以上才能使用。

如果要修改项目的端口，在package.json里面配置就可以了，示例如下：
比如配置egg为7002，webpack为8008
"scripts": {
    "pro": "EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &",
    "dev": "npm run server & npm run dev_static",
    "dev_static": "webpack-dev-server **--port 8080** --inline --hot --watch --progress --config ./static/build/webpack.dev.config.js",
    "build": "webpack  --progress --config ./static/build/webpack.prod.config.js && node ./scripts/copy.js",
    "server": "egg-bin dev  **--port 7002",**
    "debug": "egg-bin debug",
    "test": "egg-bin test"
  },
里面的静态目录的配置文件，也要改下服务器端口，里面对应的服务器7001改为7002就可以了。
**egg-restapi-module-tool/static/src/utils/config.js**
