### ISSUE TITLE
Failed to load resource:     net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by chaserH** [fomenyesu/egg-restapi-module-tool#7]
运行项目，填写用户名密码，一直显示加载用户信息，打开控制台发现很多这样的报错：
Failed to load resource:     
net::ERR_CONNECTION_TIMED_OUT
Error: Network Error
    at e.exports (index.js:6)
    at XMLHttpRequest.p.onerror (index.js:6)
请问该怎么解决？

**Comment by fomenyesu** [comment]
这个报错应该是服务器没有连接上MYSQL 数据库的报错信息。
需要检查你的MYSQL连接配置。
