### ISSUE TITLE
现在正常安装后，npm run server 命令会直接显示报错

### ISSUE THREAD

**Issue by lyh1091106900** [fomenyesu/egg-restapi-module-tool#9]
现在正常安装后，npm run server 命令会直接显示报错，node版本6.9.5和8.9.3都会报错，报错的原因不一样

**Comment by fomenyesu** [comment]
请检查你的MYSQL连接配置。获取贴出对应的版本报错信息给我分析。谢谢！
[config.local.js文件](https://github.com/fomenyesu/egg-restapi-module-tool/blob/master/config/config.local.js)
